### ISSUE TITLE
Share Option

### ISSUE THREAD

**Issue by DominikAngerer** [mikepenz/wall-splash-android#1]
Would it be possible to add something like a share option for every image?

I will come back with some ideas.

**Comment by mikepenz** [comment]
@DominikAngerer nice idea. i will look how i can implement this.

**Comment by DominikAngerer** [comment]
@mikepenz thanks! Looking forward to see this in the app. Any ideas for the interaction design?

**Comment by mikepenz** [comment]
feature included in version v1.5.0

**Comment by DominikAngerer** [comment]
Looking create ;)
